// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEC5as_dTFyBO1wE7oJoXPwKmZ4j8V2Dw',
    appId: '1:225575037507:web:1986d1bd99b934802cc2f6',
    messagingSenderId: '225575037507',
    projectId: 'noor-fashion-shop',
    authDomain: 'noor-fashion-shop.firebaseapp.com',
    storageBucket: 'noor-fashion-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5s53gRFxUueksdi84A4p2laMCq8KXRU',
    appId: '1:225575037507:android:d98a75ae45887cc12cc2f6',
    messagingSenderId: '225575037507',
    projectId: 'noor-fashion-shop',
    storageBucket: 'noor-fashion-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMbqr9JbOxMYILppY3ttiAPQ8KnapN2cs',
    appId: '1:225575037507:ios:ecebef72ab0909782cc2f6',
    messagingSenderId: '225575037507',
    projectId: 'noor-fashion-shop',
    storageBucket: 'noor-fashion-shop.firebasestorage.app',
    iosBundleId: 'com.example.noorFashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMbqr9JbOxMYILppY3ttiAPQ8KnapN2cs',
    appId: '1:225575037507:ios:ecebef72ab0909782cc2f6',
    messagingSenderId: '225575037507',
    projectId: 'noor-fashion-shop',
    storageBucket: 'noor-fashion-shop.firebasestorage.app',
    iosBundleId: 'com.example.noorFashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEC5as_dTFyBO1wE7oJoXPwKmZ4j8V2Dw',
    appId: '1:225575037507:web:c8e7e75d0586fe3b2cc2f6',
    messagingSenderId: '225575037507',
    projectId: 'noor-fashion-shop',
    authDomain: 'noor-fashion-shop.firebaseapp.com',
    storageBucket: 'noor-fashion-shop.firebasestorage.app',
  );

}